# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------

name: integration-ci

on:
  push:
    branches-ignore:
      - master
    paths:
      - 'feed-generator/**'
      - 'hashtag-actor/**'
      - 'hashtag-counter/**'
      - 'message-analyzer/**'
      - 'snapshot/**'
      - 'validation-worker/**'
  pull_request:
    branches-ignore:
      - master
    paths:
      - 'feed-generator/**'
      - 'hashtag-actor/**'
      - 'hashtag-counter/**'
      - 'message-analyzer/**'
      - 'snapshot/**'
      - 'validation-worker/**'

env:
  IMAGES: '"feed-generator" "hashtag-actor" "hashtag-counter" "message-analyzer" "snapshot" "validation-worker"'

jobs:
  build:
    name: build feed-generator
    runs-on: ubuntu-latest
    env:
      APP_REGISTRY: ${{ secrets.DOCKER_HASHTAG_APP_REGISTRY }}
      # TODO: APP_VER needs to be versioned correctly
      APP_VER: dev
      ARTIFACT_DIR: ./deploy_artifact
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: docker login
        if: github.event_name != 'pull_request'
        run: |
          docker login -u ${{ secrets.DOCKER_REGISTRY_ID }} -p ${{ secrets.DOCKER_REGISTRY_PASS }}
      - name: Build feed-generator app docker image
        run: |
          docker-compose build

          declare -a arr=(%{{ env.IMAGES }})

          for i in "${arr[@]}"
          do
            echo "Tagging docker image ${i}"
            docker tag $i ${{ env.APP_REGISTRY }}/${i}:${{ env.APP_VER }}
            docker push ${{ env.APP_REGISTRY }}/${i}:${{ env.APP_VER }}
          done
      - name: Copy deployment yaml to archieve
        run: |
          mkdir -p ${{ env.ARTIFACT_DIR }}
          cp ./longhaul-test/*.yml ${{ env.ARTIFACT_DIR }}
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: longhaul-test
          path: ${{ env.ARTIFACT_DIR }}
  deploy:
    name: deploy longhaul applications to test cluster
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    env:
      APP_NAMESPACE: longhaul-test
      TEST_CLUSTER_NAME: dapr-seattle
      TEST_RESOURCE_GROUP: dapr-test
      ARTIFACT_DIR: ./deploy_artifact
    steps:
      - name: download artifacts
        uses: actions/download-artifact@master
        with:
          name: longhaul-test
          path: ${{ env.ARTIFACT_DIR }}
      - name: Login Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_LOGIN_USER }} -p ${{ secrets.AZURE_LOGIN_PASS }} --tenant ${{ secrets.AZURE_TENANT }} --output none
      - name: Set up kubeconf for longhaul test environment
        run: |
          az aks get-credentials -n ${{ env.TEST_CLUSTER_NAME }} -g ${{ env.TEST_RESOURCE_GROUP }}
      - name: Deploy apps to longhaul test environment
        run: |
          declare -a arr=(%{{ env.IMAGES }})

          for i in "${arr[@]}"
          do
            echo "Deploy image ${i}"
            kubectl apply -n ${{ env.APP_NAMESPACE }} -f ${{ env.ARTIFACT_DIR }}/${i}-deploy.yml & kubectl rollout restart -n ${{ env.APP_NAMESPACE }} deploy/${i}-app
          done
          
